### ISSUE TITLE
Land Use Todo List

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/suitability-analysis#43]
- [ ] resample regions to 25m
- [ ] either download data up to year of most recent move or resample the historic to 30m instead
- [ ] Add attribute to relocatedtown to store the data
- [ ] add in workflow that processes that attribute - ideally controlled directly from relocatedtown instead of from the polygonstatistics option
- [ ] Use http://scikit-learn.org/stable/modules/feature_extraction.html that page to turn the categorical values into appropriate numeric fields.

**Comment by nickrsan** [comment]
May want to downsample to 1m (or another common denominator), then up to 30 for the match. I think most of these tasks are done, but should be confirmed once working on land use again

**Comment by nickrsan** [comment]
I think this was all done, and land use was tossed because it didn't factor in.
